version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - FLASK_ENV=development

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: Myapp_base
      MYSQL_ROOT_PASSWORD: examsecret
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: